"""empty message

Revision ID: 00368ab45d55
Revises: 36728834362a
Create Date: 2018-05-06 14:57:40.167733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00368ab45d55'
down_revision = '36728834362a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comment_doctor_id'), 'comment', ['doctor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_doctor_id'), table_name='comment')
    op.drop_column('comment', 'doctor_id')
    # ### end Alembic commands ###
