"""empty message

Revision ID: 30e8c2f10285
Revises: 70d6f366a3c1
Create Date: 2018-05-02 21:46:21.462186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e8c2f10285'
down_revision = '70d6f366a3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors_specialties',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialty.id'], ),
    sa.PrimaryKeyConstraint('doctor_id', 'specialty_id')
    )
    op.add_column(u'doctor', sa.Column('address', sa.JSON(), nullable=True))
    op.add_column(u'doctor', sa.Column('group_id', sa.String(length=255), nullable=True))
    op.add_column(u'doctor', sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True))
    op.add_column(u'doctor', sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True))
    op.create_index(op.f('ix_doctor_group_id'), 'doctor', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_group_id'), table_name='doctor')
    op.drop_column(u'doctor', 'longitude')
    op.drop_column(u'doctor', 'latitude')
    op.drop_column(u'doctor', 'group_id')
    op.drop_column(u'doctor', 'address')
    op.drop_table('doctors_specialties')
    op.drop_table('specialty')
    # ### end Alembic commands ###
