"""empty message

Revision ID: 5117ae96d555
Revises: 00368ab45d55
Create Date: 2018-05-06 15:14:26.199371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5117ae96d555'
down_revision = '00368ab45d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comment_active', table_name='comment')
    op.drop_index('ix_comment_author_id', table_name='comment')
    op.drop_index('ix_comment_doctor_id', table_name='comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comment_doctor_id', 'comment', ['doctor_id'], unique=False)
    op.create_index('ix_comment_author_id', 'comment', ['author_id'], unique=False)
    op.create_index('ix_comment_active', 'comment', ['active'], unique=False)
    # ### end Alembic commands ###
