"""empty message

Revision ID: fb60ad7af9b4
Revises: 5117ae96d555
Create Date: 2018-05-06 15:17:21.952515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb60ad7af9b4'
down_revision = '5117ae96d555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comment_active'), 'comment', ['active'], unique=False)
    op.create_index(op.f('ix_comment_author_id'), 'comment', ['author_id'], unique=False)
    op.create_index(op.f('ix_comment_doctor_id'), 'comment', ['doctor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_doctor_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_author_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_active'), table_name='comment')
    # ### end Alembic commands ###
