"""empty message

Revision ID: fce8d45c9c71
Revises: f783f88aaf62
Create Date: 2018-05-03 14:41:01.885533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fce8d45c9c71'
down_revision = 'f783f88aaf62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('archive', sa.Boolean(), nullable=True))
    op.drop_column('comment', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('comment', 'archive')
    # ### end Alembic commands ###
